image: node:latest


before_script:
  - node -v
  - npm -v
  - apt-get update -qq && apt-get install -y -qq
  - npm install


stages:
  - prep
  - build
  - deploy


prep:
  stage: prep
  script:
    - rm *
    - npm install
  artifacts:
    paths:
      - node_modules
  cache:
    paths:
      - node_modules
  only:
    - master


build:
  stage: build
  script:
    - npm run prod
  artifacts:
    paths:
      - dist
  only:
    - master


staging:
  stage: deploy
  script:
    - cd dist
    - ls
  only: 
    - master